### PR TITLE
Update verilator patterns

### PR DESCRIPTION
**Pull request by cpitclaudel**

### CODE REVIEW

**Comment by cpitclaudel** [comment]
We'll need to update the version number in the docker build machine for the tests to pass.

**Comment by fmdkdd** [comment]
The docker image just installs the version that is in the repositories of Ubuntu 18.04, unfortunately.  We could probably try bumping the Ubuntu version used, but 20.04 is just around the corner.

We can just remove verilator from the image so the CI just doesn't test it until we bump.

**Comment by cpitclaudel** [comment]
> The docker image just installs the version that is in the repositories of Ubuntu 18.04, unfortunately. We could probably try bumping the Ubuntu version used, but 20.04 is just around the corner.

I think it's OK to wait for a while; verilator isn't very easy to upgrade outside of using the repos, so we can wait to merge this.

**Comment by DanielVukelich** [comment]
Ubuntu 20.04 LTS released on April 23.  Any chance that this could merge now?

**Comment by cpitclaudel** [comment]
Let's wait until September to get people a bit of time to upgrade?

**Comment by MikeWalrus** [comment]
@cpitclaudel  Why is this still not merged? Even Ubuntu 22.04 LTS has come out. :)

**Comment by cpitclaudel** [comment]
Thanks for the reminder!

**Pull request merged**
