### PR TITLE
Add @ghprince to lua team

### PR DESCRIPTION
**Pull request by lunaryorn**
Following up their great work in #1047 and #1057 I'd like to add @ghprince as a regular contributor for a to-be-created Lua team.

@cpitclaudel Do you agree?

# TODO

- [x] Create Lua team in org
- [x] Invite @ghprince to lua team and the contributors team
- [x] @ghprince has accepted :blush:
- [x] Add @ghprince to our internal developer gitter chat.

### CODE REVIEW

**Comment by lunaryorn** [comment]
FTR, LGTM.

**Comment by cpitclaudel** [comment]
Yes, wonderful :) LGTM

**Comment by lunaryorn** [comment]
@ghprince Please add a comment to this issue when you've accepted the invitation so that I can send you an invitation for the internal developer chatroom on Gitter.

**Comment by ghprince** [comment]
@lunaryorn thx! I have just accepted the invitation.

**Comment by lunaryorn** [comment]
@ghprince Welcome on board.   It's awesome to have you in our team!

Please read through our [Contributor's Guide](http://www.flycheck.org/en/latest/contributor/contributing.html) and our [Maintainer's Guide](http://www.flycheck.org/en/latest/contributor/maintaining.html) to understand how we're working in Flycheck, and please internalize our [Code of Conduct](http://www.flycheck.org/en/latest/community/conduct.html) as it's the basis of our efforts to create a safe friendly and welcoming environment for all contributors.

We'll mention you whenever a Lua issue pops up, but please feel free to take a look at other issues as well.  The Lua team is just for communication, please feel free to take a look at other areas of Flycheck, too!

Thanks a lot for joining us :blush:

**Comment by lunaryorn** [comment]
That is awesome!  It's a pleasure to work with you 😊

**Pull request merged**
