### PR TITLE
Add `flycheck-` prefix to rebar3 defuns

### PR DESCRIPTION
**Pull request by fmdkdd**
Somehow missed that when reviewing.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
LGTM; just needs he conflict fixed

**Comment by purcell** [comment]
Doh, sorry, I just spotted and fixed this independently, plus a couple of other unprefixed symbols.

**Comment by fmdkdd** [comment]
@purcell Was this spotted using the updated `package-lint`?  Good catch.

**Comment by purcell** [comment]
> Was this spotted using the updated `package-lint`? Good catch.

Nope, just with the previous version. The prefix checks have been around for a while now.

I'd actually really like to run `package-lint` on everything as part of building MELPA packages, but a key limitation is that it currently only understands single-file packages, so it can't scan secondary `.el` files with an understanding of the overall package name and dependencies.

It's a good thing to use in CI builds, IMO, and hopefully fairly easy to do.

**Comment by fmdkdd** [comment]
If it had no false positives, we would gladly had it to the CI.  That would prevent errors from getting into MELPA, and save you the work of reporting them back to us ;)

**Comment by purcell** [comment]
> If it had no false positives, we would gladly had it to the CI. That would prevent errors from getting into MELPA, and save you the work of reporting them back to us ;)

That should *mostly* be the case once the PR is merged which bumps the minimum Emacs version. The only two remaining notes would be those about `less-css-mode` and `scss-mode`, which can be eliminated by converting (for example) `:modes (scss-mode)` to the equally-valid `:modes scss-mode`, which `package-lint` doesn't take to be a function call.

**Comment by purcell** [comment]
Ah, not quite:
```
6803:1: error: `flycheck-c/c++-quoted-include-directory' contains a non-standard separator `/', use hyphens instead (see Elisp Coding Conventions).
```
This might be fixable in `package-lint`, though I have to be careful because people love to spam `/` into their symbol names... :-)

**Comment by purcell** [comment]
Hmm, looks like that's not easy to fix without missing real cases I want `package-lint` to whine about.

**Comment by cpitclaudel** [comment]
How hard would it be to extend package-lint to have an explicit exclude list?

**Comment by purcell** [comment]
It wouldn't be hard, I guess. I'm not averse to the idea.

**Comment by cpitclaudel** [comment]
That might be the easiest and mot flexible solution, then.  I'd be happy to have package-lint running on every build :)

**Pull request closed without merging**
