### PR TITLE
Add Emacs Lisp other initialization option.

### PR DESCRIPTION
**Pull request by QBobWatson**
This adds a simple option to the emacs-lisp checker to have flycheck evaluate an arbitrary piece of code before checking a file.  I use it to (require 'my-globals).

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Thanks. I'm not sure how much I like the idea of running arbitrary code, though.  Can you clarify the use case? Is it for your .emacs.d? If so, you could locally advise `flycheck-option-emacs-lisp-package-initialize`, for example.

**Comment by QBobWatson** [comment]
I just want to require the file that defines my load-path.  How about this?  It's just an option for extra requires.

**Comment by cpitclaudel** [comment]
Understood.  I'm grateful for the contribution, but I'm just not sure how generally useful this feature would be.  Concretely, the only use is for init files, right?

**Comment by QBobWatson** [comment]
Yes, that's correct. But most Emacs users will only ever open an emacs-lisp buffer when editing their config files, and some people have very extensive configuration :)

**Comment by fmdkdd** [comment]
Sorry for the delay.  I can sense @cpitclaudel's hesitation for this feature here, and I, too, am on the fence.

On the one hand, the `emacs-lisp` checker was mostly made with packages in mind, not user files.  There are warnings like "add ;;; commentary section" or "missing (provide 'package)" that make no sense for init files. 

On the other hand, @QBobWatson makes a valid point: most Emacs users who edit emacs-lisp do it for their configuration, not for hacking packages.  If they are also Flycheck, users, they might want to use the `emacs-lisp` checker as it provides, besides the spurious warnings, valid feedback for incorrect syntax.

In that sense, this PR is a step in reducing the amount of spurious warnings for this use case.

In fact, I would be interesting in pursuing further.  @QBobWatson, even with this patch,  you do get `add ;;; commentary section` for your init file, don't you?  If you can update this PR to make the spurious warnings disappear, we'll glady reconsider merging it.

**Comment by QBobWatson** [comment]
Actually, the `add ;;; commentary section` warnings and the like are in the `emacs-lisp-checkdoc` checker, which I have disabled for config files.  I'm not sure where `missing (provide 'package')` comes from, but I'm not getting those warnings anyway.

**Comment by fmdkdd** [comment]
Oooh.  You are right, I was confused there.  So, once you add the `require`, can you actually check your whole init file without errors or spurious warnings?

**Comment by QBobWatson** [comment]
That's correct -- once I add the `require` and disable `emacs-lisp-checkdoc`, I get no errors or warnings.

**Comment by fmdkdd** [comment]
Then I would say it's worth it.  What say you, @cpitclaudel?

**Comment by cpitclaudel** [comment]
> What say you, @cpitclaudel?

I don't know.  I don't really buy it.  @QBobWatson, your situation is pretty specific: part of your configuration seems to a be a proper, `require`-able file that your other configuration files depend on. If so, why not just `require` it in other configuration files?

> On the other hand, @QBobWatson makes a valid point: most Emacs users who edit emacs-lisp do it for their configuration, not for hacking packages. If they are also Flycheck users, they might want to use the emacs-lisp checker as it provides, besides the spurious warnings, valid feedback for incorrect syntax.

Fair enough.  But in that case do we actually need such a general setting?  Wouldn't it be enough to just add a list or extra packages?

An alternative solution would be for Flycheck to set a variable while checking ELisp files. Something like `flycheck-elisp-in-process`.  Then users could write:

```
(when (bound-and-true-p 'flycheck-elisp-in-process)
  … extra init code here …)
```

**Comment by fmdkdd** [comment]
>  Wouldn't it be enough to just add a list of extra packages?

The latest commit just adds a list of features to be required.  Aren't they the same?

@QBobWatson can you give us a glimpse of your init file to see how you would use that feature, and what exact errors or warnings it allows you to get rid of?

It seems the crux of the issue is whether adding such a feature would be beneficial to many Flycheck users, or for those who have set up their init files in a way similar to yours.  And, whether there are alternative way of achieving the same result.

**Comment by cpitclaudel** [comment]
> The latest commit just adds a list of features to be required. Aren't they the same?

They are, sorry :)

Thinking more about this: why isn't the following sufficient?

```
(cl-eval-when (compile)
  (require 'my-globals))
```

**Comment by QBobWatson** [comment]
It was a couple years ago that I set all this up, but here's what I remember of my reasoning.

I have about 50 init files for different subsystems, which are all `load`ed by `init.el`.  Now, `init.el` requires `my-globals`, so `(require 'my-globals)` is not needed in my init files at runtime or compile time.  So the only reason to `(require 'my-globals)` in those files would be for flycheck.

Of course I could do this, but my opinion is that the emacs-lisp checker should be able to set itself up to check the file in the same context as it will be used, to the extent this is possible.  Initialization files are often not run as standalone packages.  Since the change to flycheck's code is minimal, I thought it would be worth adding.

**Comment by cpitclaudel** [comment]
> Of course I could do this, but my opinion is that the emacs-lisp checker should be able to set itself up to check the file in the same context as it will be used,

Thanks for clarifying.  What confuses me is that you'll end up using this:

```
;; -*- flycheck-emacs-lisp-require-features: (my-globals) -*-
```

… instead of that:

```
(require 'my-globals)
```

Is there any reason to prefer the first one? (especially given that it'll trigger a risky-variable warning).

**Comment by QBobWatson** [comment]
> Is there any reason to prefer the first one? (especially given that it'll trigger a risky-variable warning).

I have my config set up to do the `flycheck-emacs-lisp-require-features` and disable `emacs-lisp-checkdoc` automatically for all the config files in that directory.  This happens in `emacs-lisp-mode-hook`.

**Comment by cpitclaudel** [comment]
I think I'll defer to @fmdkdd, but I'm not sold.  This sounds like a very specific setup, and it's not clear how useful that setting would be for others (especially since `require` is just one more line)

**Comment by fmdkdd** [comment]
>  it's not clear how useful that setting would be for others

You hit the nail on the head.

I'd be happy to help you make your config neater @QBobWatson, but the workarounds suggested in this thread look sufficient for this use case to me.  The fact that it's a slightly risky option (as it tells Emacs to load arbitrary code, after all) doesn't help either. 

Unless we know for sure it's a major pain point for using the `emacs-lisp` checker, or unless you can think of another usefulness for this option, it is not enough to warrant inclusion.

**Comment by QBobWatson** [comment]
> Unless we know for sure it's a major pain point for using the emacs-lisp checker, or unless you can think of another usefulness for this option, it is not enough to warrant inclusion.

I understand your point.  It's probably best if I just maintain a patch for my own use.

**Comment by fmdkdd** [comment]
@QBobWatson Thank you for taking the time to discuss this feature with us.

**Pull request closed without merging**
