### PR TITLE
Fix tracking of temporary files in ELisp checker

### PR DESCRIPTION
**Pull request by cpitclaudel**
Closes GH-1689.  This is due to Emacs now running --eval in lexical mode.

### CODE REVIEW

**Comment by zw963** [comment]
So wired,  why i can't found out "fix-1689-lexical-eval" branch?

```sh
 ╰─ $ git checkout fix-1689-lexical-eval
error: pathspec 'fix-1689-lexical-eval' did not match any file(s) known to git

 ╭─ 23:37  zw963 ⮀ ~/Git/flycheck ⮀ ⭠ (f77c3c0f) master u=  ➦ ruby-2.6.3
 ╰─ $ 1  git branch -r
  origin/HEAD -> origin/master
  origin/master
 ╰─ $ 1  git remote -v
origin  https://github.com/flycheck/flycheck (fetch)
origin  https://github.com/flycheck/flycheck (push)
 ╰─ $ git fetch --all
Fetching origin

```

**Comment by zw963** [comment]
@cpitclaudel , following is my newest master branch, how can i test based you this patch?

image

**Comment by cpitclaudel** [comment]
OK, super.  I'll wait for a few days to see if @fmdkdd has time for a review and then I'll merge.

**Comment by cpitclaudel** [comment]
I think this change is safe to go without further review, since I've discussed it on the emacs-devel mailing list as well.

**Pull request merged**
