### PR TITLE
Drop compatibility for Emacs versions below 24.5

### LINKED ISSUE #1597: flycheck-verify-setup: wrong-type-argument sequencep 0
I was trying to sort out a flawed checker definition (I am editing files in a virtualenv with a different set of linting tools (python3), and the checkers in emacs seemed to be using platform defaults (python 2.7) rather than the project's). 

I've done list-package, hit 'U' to upgrade my packages, and then 'x' to install the updates. But now, after the update, when I run flycheck-verify-setup in a python buffer, i get the error `(wrong-type-argument sequencep 0)`

I don't get the error in a markdown or text buffer (conditions for which I have no checkers installed).

I have normally pylint and pyflakes checkers working in python. 

The stacktrace is:

```
Debugger entered--Lisp error: (wrong-type-argument sequencep 0)
  mapconcat(#[257 "\300\301!\302\303\304\305C&\207" [make-text-button symbol-name nil type help-flycheck-checker-doc help-args] 8 "\n\n(fn CHECKER)"] (python-flake8) ", ")
  flycheck--verify-next-checkers(python-mypy)
  flycheck--verify-princ-checker(python-mypy #<buffer my_file.py>)
  flycheck-verify-setup()
  call-interactively(flycheck-verify-setup record nil)
  command-execute(flycheck-verify-setup record)
  execute-extended-command(nil "flycheck-verify-setup")
  call-interactively(execute-extended-command nil nil)
```

My environment:
  -  emacs 24.3.1 (ancient).
  - (pkg-info-library-version 'flycheck) returns "32alpha"
  - flycheck-version reports 32alpha package: 20190704.926
  - ubuntu 14.04 (ancient)
  
Steps to reproduce:

  - open a python buffer. (emacs vs emacs -Q makes no difference)
  - flycheck-mode (on)
  - run flycheck-verify-setup
  - error is printed

The ancient software could be to blame, but it used to work before the package update. Maybe I can rollback. Whenever I save a buffer in my python3 project, I get a stack trace which looks like a python2 executable is trying to go through python3 modules -- and I'm invited to install a more recent version of python-pylint.

ps The contributor guide points to https://swsnr.de/2015/11/29/reproduce-bugs-in-emacs-Q.html , but it gives me 404.

### PR DESCRIPTION
**Pull request by fmdkdd**
Fix #1597.

I've also dropped compatibility shims for 24.3 and 24.4.

### CODE REVIEW

**Comment by marsam** [comment]
Would you mind creating a release tag before merging this?

**Comment by fmdkdd** [comment]
CI error with flake8 seems to be from [this](https://gitlab.com/pycqa/flake8-docstrings/issues/36).

@marsam Sure, probably a good idea as well.  I don't think we have any outstanding critical bugs.  I would have liked #1400 to make it though.  @cpitclaudel WDYT?

**Comment by cpitclaudel** [comment]
I would have loved that too, but I haven't found the time to work on it lately :/

**Review by cpitclaudel — APPROVED** [review]
LGTM.  Thanks for this.

**Comment by purcell** [comment]
I've been working on updating `package-lint` so that it understands much more about which libraries and functions were added/removed in the various Emacs versions. So as a test I've been running it on `flycheck.el`. In this branch, here's some relevant stuff it says:

```
75:10: error: You should depend on (emacs "25.1") if you need `subr-x'.
1494:11: error: You should depend on (emacs "25.1") if you need `string-empty-p'.
2066:18: error: You should depend on (emacs "25.1") if you need `string-join'.
3532:13: error: You should depend on (emacs "25.1") if you need `string-empty-p'.
3823:25: error: You should depend on (emacs "25.1") if you need `string-trim'.
3825:21: error: You should depend on (emacs "25.1") if you need `string-empty-p'.
3826:23: error: You should depend on (emacs "25.1") if you need `string-empty-p'.
4814:34: error: You should depend on (emacs "25.1") if you need `string-join'.
4860:16: error: You should depend on (emacs "25.1") if you need `string-join'.
5787:11: error: You should depend on (emacs "25.1") if you need `string-join'.
6072:33: error: You should depend on (emacs "25.1") if you need `string-trim'.
6153:24: error: You should depend on (emacs "25.1") if you need `string-empty-p'.
6402:18: error: You should depend on (emacs "25.1") if you need `string-empty-p'.
6403:22: error: You should depend on (emacs "25.1") if you need `string-empty-p'.
6405:44: error: You should depend on (emacs "25.1") if you need `string-empty-p'.
8765:10: error: You should depend on (emacs "26.1") if you need `less-css-mode'.
9244:12: error: You should depend on (emacs "25.1") if you need `string-trim'.
10529:10: error: You should depend on (emacs "25.1") if you need `scss-mode'.
```

In other words, this PR would be okay if the new minimum Emacs version were 25.1, but not with it as 24.5.

**Comment by cpitclaudel** [comment]
Neat tool, thanks!  But, AFAICT, all of these are false positives: subr-x is available starting in 24.4 (in `lisp/emacs-lisp/subr-x.el`), and that's where these functions are defined. Am I missing something?

**Comment by purcell** [comment]
> Neat tool, thanks! But, AFAICT, all of these are false positives: subr-x is available starting in 24.4 (in `lisp/emacs-lisp/subr-x.el`), and that's where these functions are defined. Am I missing something?

Thanks, you're right, and that found an important problem in my work on `package-lint`. The new warnings for the `flycheck.el` on this branch are
```
8765:10: error: You should depend on (emacs "26.1") if you need `less-css-mode'.
10529:10: error: You should depend on (emacs "25.1") if you need `scss-mode'.
```
though those are a little bogus because they look like function calls to `package-lint`, and it can't fully understand the code.

**Comment by cpitclaudel** [comment]
Thanks!

**Comment by cpitclaudel** [comment]
We'll merge this after the next release

**Comment by purcell** [comment]
> Let's just drop Emacs 24 altogether, 

Very reasonable!

> or better yet, Emacs 25 too. The latest Ubuntu LTS still supported is 18.04, which comes with Emacs 25. Support will end next year, so you are going to have to drop Emacs 25 soon.

"Have to?" Not really. But the Ubuntu support cycle certainly might be one sign that it is more viable to do so.

**Comment by bbatsov** [comment]
I did some similar cleanup before noticing this PR, so I'll close it.

**Pull request closed without merging**
