### PR TITLE
Add `sass-stylelint' checker

### PR DESCRIPTION
**Pull request by Aankhen**
I more or less duplicated the code and docs for `scss-stylelint'.

### CODE REVIEW

**Comment by bbatsov** [comment]
@Aankhen Is this checker still relevant today?

**Comment by Aankhen** [comment]
Yes, it would still be useful.

**Comment by bbatsov** [comment]
Got it. Please, rebase on top of `master` then and mention the new checker in the changelog.

**Comment by Aankhen** [comment]
I deleted this fork a while ago, so I couldn’t push the changes here. I created a new fork for the same thing. Shall I close this PR and create a new one?

**Comment by bbatsov** [comment]
@Aankhen Yeah, that'd be best.

**Pull request closed without merging**
