### PR TITLE
Add `flycheck-tslint-args`

### PR DESCRIPTION
**Pull request by fmdkdd**
Closes GH-1184 (which see).

### CODE REVIEW

**Comment by fmdkdd** [comment]
Sorry @cpitclaudel, I did not mean to skip your approval.  They made the green merge button too tempting.

Are you ok with this going in flycheck?  It seemed harmless enough since we already have such options for other checkers. (Next time I'll remember to ask *before* merging).

**Comment by cpitclaudel** [comment]
> Are you ok with this going in flycheck? It seemed harmless enough since we already have such options for other checkers.

Yup!

> (Next time I'll remember to ask before merging).

Please don't :) I welcome every opportunity to delegate, and I fully trust your judgment on these small issues :) Reverting commits is easy if something goes wrong, and we have plenty of tests.

**Comment by fmdkdd** [comment]
@cpitclaudel Noted, thanks :)

**Comment by everedifice** [comment]
How can i pass this arguments?

I spent many time for passing arguments. is there any example for this?

**Comment by cpitclaudel** [comment]
Yes: revert to the default, and use the "Ins" button to insert entries. Currently you're passing a single argument `"--project" … "--type-check"`.

**Pull request merged**
