### PR TITLE
Typo fixes for flycheck-versus-flymake.rst

### PR DESCRIPTION
**Pull request by msherry**
Small typo fixes.

### CODE REVIEW

**Comment by fmdkdd** [comment]
Thanks for noticing these.

Actually, I guess this:
> Contributing to Flycheck does not require a copyright assignment.

is not true anymore, since we make all contributors accept the contributor license agreement.  

cc @cpitclaudel

**Comment by cpitclaudel** [comment]
The part about copyright assignments is still true, actually : we require a CLA but not an assignment

**Comment by fmdkdd** [comment]
Oh, so I'm confused about the difference between the two situations. 

Is it that, in the assignment case, the FSF is the sole copyright owner of all the code, but with a CLA, the individuals retain their copyright and agree to waive parts of it for the situations specified by the license?

**Comment by cpitclaudel** [comment]
Essentially, yes. With a CLA we as maintainers have no more rights or ownership over the code than other contributors: we essentially have the freedoms afforded by the GPL, but nothing more; each individual author retains sole copyright of their code.  With an FSF-style assignment, ownership of the code goes to the FSF.

**Comment by fmdkdd** [comment]
Okay, I think I got it.  I've reworded the paragraph in c114b38 to explicitly mention the CLA.

**Pull request merged**
