### PR TITLE
use erlc on .erl only

### PR DESCRIPTION
**Pull request by massemanet**
flycheck (not unreasonably) tries to run all buffers with erlang-mode through the erlang compiler. Alas, it is quite common to have files that use erlang-mode but does not compile (e.g. header and config files).

also see #1198

### CODE REVIEW

**Comment by fmdkdd** [comment]
That looks harmless.  Except you lose the ability to check Erlang buffers not associated with files, and Erlang buffers that do not have files ending in `.erl`.  Though this might be a lesser inconvenience than having spurious errors for headers.

I have never used Erlang, but I find it curious that the Erlang compiler doesn't checks header files though.  Can't they have errors?  Is a separate tool used to validate header files?

`git blame` tells me @syl20bnr wrote the checker (in 2013), and @yzprofile added the library-path variable (in 2015).  They may have useful insight (or they may never this thread ;).

**Comment by massemanet** [comment]
The erlang compiler can compile several different languages. It decides which kind of compilation to do based on the file name extension; a file with erlang source code must end with .erl.
  Thus, it does not make sense to have erlang code in a file that does not end with .erl. Header files can not be checked separately because they are not compilable. 
  Checking buffers without a backing file does not work because (as far as I can tell) there is no way to make flycheck create a temp file with the .erl extension.

**Comment by fmdkdd** [comment]
Thanks for enlightening me.  So, currently the Erlang checker will run on header files by itself (and all files in erlang-mode), and will produce spurious errors?  Or does it just fail silently?

In either case, I agree that not running the checker is best.  In fact, you should probably use the `:enabled` checker property for that instead of `:predicate`, since `:enabled` is run once for the buffer whereas `:predicate` is run every time a syntax check is triggerred (i.e., after every text change by default).

**Comment by massemanet** [comment]
Currently, it runs on all files in erlang-mode, and fails noisily on all but the .erl files.

  `:enabled` is indeed what I want. Thanks for pointing it out. I will update the PR soonish.

**Comment by fmdkdd** [comment]
Thank you very much for your contribution, and happy hacking 👍

**Comment by cpitclaudel** [comment]
@fmdkdd @massemanet 👍 🎉

**Pull request merged**
