### PR TITLE
[WIP] Add a Python type checker using MyPy

### PR DESCRIPTION
**Pull request by cpitclaudel**
I think we'll hold this until we merge the next-checker stuff :) This is a checker for [MyPy](http://www.mypy-lang.org/). Types!

### CODE REVIEW

**Comment by dakra** [comment]
Any news on this? I would like mypy support :)

**Comment by cpitclaudel** [comment]
@dakra Can you try the branch and report whether it works for you? That would help :)

**Comment by dakra** [comment]
I tried your changes and seems to work fine.

I had to rename a few command line arguments:
`--suppress-error-context` is now `--hide-error-context`
and instead of `--silent-imports` I always use `--follow-imports=skip` (since we never want to return errors from different files?!) and and replaced the original `--silent-imports` with `--ignore-missing-imports`.

I didn't play around with it too much but lgtm :+1:

**Comment by fmdkdd** [comment]
@cpitclaudel Do you still want to wait for the `next-checker` changes?  I'd rather have that working now than in an hypothetical future ;)

**Comment by fmdkdd** [comment]
Closing in favor of #1354.

**Pull request closed without merging**
