### PR TITLE
New Sphinx website

### PR DESCRIPTION
**Pull request by lunaryorn**
This is the start of a new website and manual written with Sphinx, following #901.

[Readthedocs](https://readthedocs.org/projects/flycheck/) already builds this branch, a preview is available at http://flycheck.readthedocs.org/en/sphinx-doc/.

The site already contains our meta-documentation (CoC, contributing, etc.) and the list of supported languages, plus most of the extensions to document Emacs Lisp with Sphinx.

The manual itself is still missing, but a single-page HTML build of the old one is included, until it's been rewritten in Texinfo.

As things stand, I'd merge this pull request asap, and point `http://www.flycheck.org` to the new site, and then start to port the manual in `master`.

### CODE REVIEW

**Comment by lunaryorn** [comment]
@cpitclaudel Do you have an account on ReadTheDocs?  I'll give you admin access to the Flycheck project there.

**Comment by cpitclaudel** [comment]
I think it all looks good :) Great progress. I'm cpitclaudel on readthedocs.

I just noticed the very quick start section. It's a great way to get people to try the package, but maybe we should make it clearer that it's just for a test run? If I understand it correctly, it will install Flycheck but it won't register melpa persistently, so subsequent updates won't be downloaded, correct?

**Comment by lunaryorn** [comment]
@cpitclaudel Indeed we should emphasise that it's not permanently installed this way.

I guess we better rename the section to "Try out".

**Comment by lunaryorn** [comment]
@cpitclaudel I merged the branch, added you as a maintainer on RTD and updated the very quick start section.

**Comment by lunaryorn** [comment]
And now http://www.flycheck.org points to the readthedocs site.  I'll remove flycheck.github.io this evening when the change has propagated.

**Pull request merged**
