### PR TITLE
Formerly remove @lunaryorn from the maintainers

### PR DESCRIPTION
**Pull request by fmdkdd**
See GH-1177.

Though it saddens me, that ship has sailed.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Thanks. And thanks to you for your work and dedication!

**Comment by fmdkdd** [comment]
@cpitclaudel Glad to help!  In fact, I would be glad to join you as a maintainer, if you'd like to share the load officially ;)

**Comment by cpitclaudel** [comment]
Absolutely! Why was I under the impression that this happened last week? :)
I'll be very happy to merge a PR updating the list of maintainers ^^

**Comment by fmdkdd** [comment]
@cpitclaudel I was indeed made an owner, but wanted to ask you first.

Aaand, I pushed 0a83263 to master when I thought I was pushing to a branch.  Oh well.

**Pull request merged**
