### PR TITLE
Update test suite expected values for GCC 6

### PR DESCRIPTION
**Pull request by spwhitton**
Update test suite expected values for GCC 6

### CODE REVIEW

**Comment by lunaryorn** [comment]
LGTM.

Thanks for your work. Awesome that you take care of our test suite! 😊

**Comment by lunaryorn** [comment]
The test failure looks like a random fluke. I'll start the build again tomorrow.

**Comment by spwhitton** [comment]
No problem.  Hopefully Travis passes tomorrow.

**Comment by cpitclaudel** [comment]
LGTM; thanks! I've restarted the build.

**Comment by lunaryorn** [comment]
@spwhitton I've forcibly merged this change, and dropped 24.3 from our travis CI configuration.  It's too flaky.

**Pull request merged**
