### PR TITLE
Update test suite perl expected value

### PR DESCRIPTION
**Pull request by spwhitton**

### CODE REVIEW

**Comment by lunaryorn** [comment]
LGTM.

**Comment by cpitclaudel** [comment]
LGTM too. May be worth a bug report on the perl side, since there seems to be a missing parens in that message.

**Comment by spwhitton** [comment]
On Tue, Aug 23, 2016 at 12:08:38PM -0700, Clément Pit--Claudel wrote:
> LGTM too. May be worth a bug report on the perl side, since there seems to be a
> missing parens in that message.

Whoops.  That's my patch that's wrong.  I'll push another commit when I
get in range of my SSH key -- thanks!

-- 
Sean Whitton

**Comment by lunaryorn** [comment]
@cpitclaudel Thanks for reviewing and catching this!

@spwhitton Please amend the commit and force-push to the branch.  Once Travis CI has passed you can squash-merge right away 😊

**Comment by lunaryorn** [comment]
Thanks. Merged.

@cpitclaudel Thanks for reviewing, and catching the mistake.

**Pull request merged**
