### PR TITLE
Add @aaronjensen to our Elixir team

### PR DESCRIPTION
**Pull request by lunaryorn**
Follow up to #1063. @cpitclaudel Do you agree?

# TODO

- [x] Invite @aaronjensen to the contributors and elixir teams.
- [x] @aaronjensen accepted the invitation.
- [x] Invite @aaronjensen to our internal developers channel.

### CODE REVIEW

**Comment by lunaryorn** [comment]
LGTM. @aaronjensen While waiting for @cpitclaudel's feedback please read through our [Contributor's Guide](http://www.flycheck.org/en/latest/contributor/contributing.html) and our [Maintainer's Guide](http://www.flycheck.org/en/latest/contributor/maintaining.html) to see how we're working in Flycheck, and please internalize our [Code of Conduct](http://www.flycheck.org/en/latest/community/conduct.html) which is the basis of the safe friendly and welcoming environment we'd like to create of all users and contributors alike.

Many many thanks for helping out!

**Comment by cpitclaudel** [comment]
This looks great (LGTM); welcome aboard!

**Comment by lunaryorn** [comment]
@aaronjensen Please leave a comment when you've accepted the invitation.

**Comment by aaronjensen** [comment]
@lunaryorn accepted. Thanks!

**Pull request merged**
