### PR TITLE
Run Python mypy checker from discovered project root

### LINKED ISSUE #1829: Mypy, circular imports, and working directory
## Checklist
- [/] I have checked existing issues for potential duplicates before creating this one.
- [ ] I have read the [Troubleshooting guide][].

## Bug description
Mypy is meant to be run from the project root. Otherwise, circular imports will occur.

## Steps to reproduce
1. Create a standard Python package,
2. Import a package with the same name as the file, e.g.:
foo.py
```python
import foo

...
```
3. Source file found twice under different module names: 'project.foo' and 'foo'

- [ ] I have read https://emacs.stackexchange.com/questions/28429/how-do-i-troubleshoot-emacs-problems

## Expected behavior
This should typecheck properly.

## System configuration
```
Syntax checkers for buffer celery.py in python-mode:

First checker to run:

  python-flake8
    - may enable:         yes
    - executable:         Found at /nix/store/lix6bnvjr9wah1fjaswlsvb50gjsdp4y-python3-3.8.5-env/bin/python3
    - configuration file: Not found
    - `flake8' module:    Found at "/nix/store/lix6bnvjr9wah1fjaswlsvb50gjsdp4y-python3-3.8.5-env/lib/python3.8/site-packages/flake8/__init__.py"
    - next checkers:      python-pylint, python-mypy

Checkers that may run as part of the first checker's chain:

  python-mypy
    - may enable:         yes
    - may run:            t
    - executable:         Found at /nix/store/lix6bnvjr9wah1fjaswlsvb50gjsdp4y-python3-3.8.5-env/bin/mypy
    - configuration file: Found at "/home/myrl/Development/aesdata/remote_server/tasks/mypy.ini"

Checkers that could run if selected:

  python-pycompile  select
    - may enable:    yes
    - executable:    Found at /nix/store/lix6bnvjr9wah1fjaswlsvb50gjsdp4y-python3-3.8.5-env/bin/python3
    - next checkers: python-mypy

Checkers that are compatible with this mode, but will not run until properly configured:

  python-pylint (automatically disabled) reset
    - may enable:         no
    - executable:         Found at /nix/store/lix6bnvjr9wah1fjaswlsvb50gjsdp4y-python3-3.8.5-env/bin/python3
    - configuration file: Not found
    - `pylint' module:    Missing; sys.path is ['/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python38.zip', '/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8', '/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/lib-dynload', '/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/lib/python3.8/site-packages', '/nix/store/lix6bnvjr9wah1fjaswlsvb50gjsdp4y-python3-3.8.5-env/lib/python3.8/site-packages']
    - next checkers:      python-mypy

  python-pyright (automatically disabled) reset
    - may enable: no
    - executable: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot
Emacs version:    28.0.50
System:           x86_64-pc-linux-gnu
Window system:    x
```

Emacs configuration:
- [/] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [ ] Doom Emacs
- [ ] Other shared configuration

## Additional notes
The closest related issue is #1711. The solution there does not fix this, but the external solution https://github.com/lbolla/emacs-flycheck-mypy/commit/d5c791f does.

Mypy is needed to be run from the project's root. I've applied the patch locally, and it works.

[Troubleshooting guide]:  https://www.flycheck.org/en/latest/user/troubleshooting.html

### PR DESCRIPTION
**Pull request by wbolster**
Running from the project root is not always necessary, but improves
module discovery, e.g. when using Python namespace packages.

Closes #1829.

### CODE REVIEW

**Comment by wbolster** [comment]
friendly ping to the maintainers. this issue affects multiple users.

it seems this pull request just needs the ‘merge’ button to be clicked; ci failures seem unrelated

**Comment by wbolster** [comment]
friendly ping @cpitclaudel since you seem to be semi-active on other python related issues.

is there any way i can convince you to click that merge button? e.g. by throwing coffee your way, or rather a donation for a coffee? :upside_down_face:

**Comment by cpitclaudel** [comment]
Haha, thanks for the offer :) But, did you see https://github.com/flycheck/flycheck/pull/1771 ?

**Comment by wbolster** [comment]
nope, i did not until now. (this pull request predates that one).

if that one solves it, also fine!

but please be aware that flycheck always passes a `--config-file` arg to `mypy` (even though that shouldn't be necessary at all i think), and that should give precedence to `mypy.ini` over `pyproject.toml` (both can exist), since `mypy` support for `pyproject.toml` is relatively new and many projects have not adopted that yet.

**Comment by cpitclaudel** [comment]
> that should give precedence to `mypy.ini` over `pyproject.toml`

I think #1771 does that, doesn't it?

**Comment by bbatsov** [comment]
@wbolster So, is this PR still needed or we can close it?

**Comment by wbolster** [comment]
seems to work these days

**Pull request closed without merging**
