### PR TITLE
Add a syntax checker for stack ghc

### PR DESCRIPTION
**Pull request by lunaryorn**
TODO

- [x] Install stack on VM
- [x] Add some unit tests?

### CODE REVIEW

**Comment by purcell** [comment]
Will this be both a `haskell-stack-ghc` and a `haskell-stack-hlint`?

**Comment by lunaryorn** [comment]
@purcell I see no point in `haskell-stack-hlint`.  You can just use `stack install hlint`, can't you?

**Comment by purcell** [comment]
Probably, but I kind of assumed that different projects could use different `hlint` versions, and that the right way to exec the correct one for the current project would be with `stack exec hlint`. Maybe I'm misunderstanding how the whole thing should work.

**Comment by lunaryorn** [comment]
@purcell I don't know, but I was under the impression that you'd just install `hlint` globally with `stack install`…  I wasn't even aware that you could install `hlint` into the per-project environment.  How do you even do that?

**Comment by purcell** [comment]
Yeah, I guess you're right. It doesn't look like there's any project-specific handling of executables. In that case, just ignore me. :-)

**Comment by purcell** [comment]
Awesomesauce - will have to give this a go. :-)

**Comment by conklech** [comment]
Stack sort of has project-specific executables. If, say, in a project using the `lts-3.0` snapshot, you run `stack build hlint`, the `hlint` binary will be installed in the snapshot directory at `stack/snapshots/arch/snapshot/compiler/bin`, and can be run within the project directory using `stack exec hlint`.

For binary packages that aren't in a snapshot, I believe the binary would be placed in the project-local `.stack-work`, but would be run the same way.

**Comment by lunaryorn** [comment]
@conklech Do people actually use project-local `hlint` variants?  I'd expect most Haskell developers to install a basic toolset (e.g. stylisch, hindent, hlint, etc.) globally…

**Comment by conklech** [comment]
That's my expectation as well. Perhaps there are compiler version specific
tools. I just wanted to observe that it's possible.

**Comment by lunaryorn** [comment]
@conklech Great, thanks for your input.  I think we don't need to provide a special `stack exec hlint` syntax checker then, and an implementation of #629 should cover this case anyway should the need arise.

**Comment by slpopejoy** [comment]
Hi, I opened the above issue, but I also want to question, why was this created as a completely separate checker? 

The definition copy-pastes all of the warning and error parsing, meaning any future changes must maintain both.

Also, the docs were changed in a way to imply that Stack and GHC are somehow different, e.g. `flycheck-ghc-language-extensions` now has "Language extensions for GHC and Stack". The extensions are for GHC only -- stack is not a compiler.

I would argue instead that `haskell-ghc` should support stack similarly to how it detects a cabal file or a sandbox.

Cheers,
Stuart

**Comment by purcell** [comment]
@slpopejoy See related discussion in https://github.com/flycheck/flycheck/issues/702. I'm still not sure the current situation is ideal, but IIRC it was the expedient choice at the time. Now that `stack` is becoming very much more widely used, it could be that we have a clearer understanding of how things should work. Any suggestions would be welcome.

**Comment by lunaryorn** [comment]
@slpopejoy Summarizing the discussion in #702, a separate syntax checker lets us re-use all the existing features for syntax checker selection.  Specifically, it 

- lets you individually disable Stack for specific projects via `flycheck-disable-checker` or `flycheck-select-checker`,
- lets you see whether stack is actually used via `flycheck-verify-setup` or in the error list,
- lets us re-use the existing logic for checking for executables and predicates,
- lets us easily account for the subtle difference between invoking plain GHC and stack GHC (e.g. pass a package database or not)
- and—most important to me—puts the use of Stack in an nice declaration definition that's easy to understand and to follow.

On the other hand, discovering stack and manipulating `:command` to support a single syntax checker definition moves the logic for using stack far away from the syntax checker definition, is less transparent to the user because there wouldn't be an easy way to see what's used anymore, and would re-invent some wheels (e.g. finding the stack executable, disabling stack).

For instance, we'd have to provide an option and interface to disable Stack, something that we get for free with a nice interface if we have a separate syntax checker definition.

To me these advantages outweight the small amount of copy-pasted code, the more since the likeliness of GHC changing their output format in incompatible ways appears to be rather low, doesn't it?  And should that—against all odds—happen we can still easily overcome this by adding support for shared error pattern definitions to Flycheck.

Summarizing, making Stack a separate syntax checker tends to play best with how Flycheck works.  We are open to better ideas, though—if you have a suggestion or a better implementation please share it.

**Comment by slpopejoy** [comment]
To my mind, the different-checker thing isn't as nice as `auto` for `haskell-process-type`, which does a great job selecting `stack-ghci` or `cabal-repl` appropriately. 

Unless I'm mistaken, I'll have to do a dir-locals hack (which I haven't had to do in a while, thanks to endless improvement of `haskell-mode`) if I want a project to select the right checker. This is indeed why I reported #847, as I've gotten used to emacs doing the right thing vis-a-vis stack or not. Presumably we can find a solution for that, and this will be suitably automatic.

Thanks for summarizing #702, I agree with the thinking there overall.

**Comment by lunaryorn** [comment]
@slpopejoy Flycheck should select the appropriate syntax checker automatically as well.  If it doesn't, that's a bug, i.e. #847.

**Pull request merged**
