### PR TITLE
Make sure checker's :predicate is invoked in its :working-directory

### PR DESCRIPTION
**Pull request by sergv**
Proposed fix for problem in #969.

### CODE REVIEW

**Comment by lunaryorn** [comment]
@sergv Thanks a lot. 

LGTM. @kthelgason could you please apply this patch and check whether it helps for #969?

**Comment by kthelgason** [comment]
Awesome, will try this out and report back in #969. Thanks @sergv!

**Comment by cpitclaudel** [comment]
LGTM; sorry for the delay!

**Comment by lunaryorn** [comment]
@cpitclaudel Never mind :)  thanks for the review.

**Comment by sergv** [comment]
@cpitclaudel Thanks for the review.

**Pull request merged**
