### PR TITLE
Cache line numbers to improve performance of flycheck-add-overlay

### PR DESCRIPTION
**Pull request by cpitclaudel**
This is a partial fix for GH-1168.  Related issues: GH-153, GH-154, GH-179,
and GH-476.

### CODE REVIEW

**Comment by lunaryorn** [comment]
Nice!  LGTM.

**Comment by lunaryorn** [comment]
I'll hopefully get to review this soon, I'm quite short of time currently.

**Comment by cpitclaudel** [comment]
No hurry :) Plus, this is a pretty core part of Flycheck, so a thorough review is in order ^^

**Comment by cpitclaudel** [comment]
Updated to not rely on `pcase-let`'s behavior when a pattern doesn't match

**Comment by cpitclaudel** [comment]
Updated again because the byte compiler doesn't like (guard) patterns :/

**Comment by manuel-uberti** [comment]
Wow, thanks for the effort.

**Comment by lunaryorn** [comment]
@cpitclaudel I looked at the comment in #1168 and it seems to suggest that this PR does not contribute much, does it?  Should we still merge it, or rather focus on the other optimisations suggested by the extensive profile in #1168?

**Comment by cpitclaudel** [comment]
Done :)

**Comment by cpitclaudel** [comment]
I'd like to go ahead and merge this soon, as it should be harmless and the performance boost would be welcome. Objections?

**Comment by cpitclaudel** [comment]
> Maybe we should point out with comments before the overlay-recenter calls that they are here for optimization purposes?

I skipped the comments because overlay-recenter doesn't rely have other purposes, but feel free to add them if you think they'd help :) Thanks for the review!

**Comment by fmdkdd** [comment]
@cpitclaudel Yeah you are right, looking at the documention is probably sufficient.

**Pull request merged**
