### PR TITLE
Add flycheck-sh-bash-args

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by fmdkdd** [comment]
Do you have an example of useful arguments that you pass to bash?

**Comment by scop** [comment]
Sure. `-O extglob` is what I would need in https://github.com/scop/bash-completion. Currently I'm using this fragile hack: https://github.com/scop/bash-completion/commit/b49a182cc68a9d69d702754c3adc0b17d50e52f6#diff-939eb0c23e9efb46517d67d1760df731

**Comment by fmdkdd** [comment]
Ok thanks! :+1:

**Comment by Thaodan** [comment]
How did  you add -O extglob when bash is executed using this?

**Pull request merged**
