### PR TITLE
adding go-revive checker

### PR DESCRIPTION
**Pull request by robert-zaremba**
Adding support for the go [revive](https://github.com/mgechev/revive) checker.

### CODE REVIEW

**Comment by fmdkdd** [comment]
Thanks!  We always welcome new checkers.

You'll need to document the checker in `doc/languages.rst` in order to pass the CI.

It would be great if you could add one or two integration tests in `test/flycheck-test.el`.  Ideally, you also want to add `revive` to our Docker image so the integration test run on CI (see the [how to](https://github.com/flycheck/docker-tools#how-to-add-a-tool)).

**Comment by robert-zaremba** [comment]
Any chance to merge this PR?

**Comment by fmdkdd** [comment]
> Any chance to merge this PR?

Well, you didn't add the required documentation.

**Comment by cpitclaudel** [comment]
Ping @robert-zaremba

**Pull request closed without merging**
