### PR TITLE
Add option to specify import directories for Sass

### PR DESCRIPTION
**Pull request by jordonbiondo**
Added support for specifying import directories for Sass
via the -I (or --load-path) option.

### CODE REVIEW

**Comment by lunaryorn** [comment]
@jordonbiondo Shouldn't we add this option to the SCSS checker as well?

**Comment by jordonbiondo** [comment]
That would make sense, I only needed a sass option at the time, so that's all I did.

**Comment by lunaryorn** [comment]
@jordonbiondo Would you mind to add the option for SCSS as well, and rebase the PR on master?

**Comment by jordonbiondo** [comment]
Yeah, I can do that.

**Comment by lunaryorn** [comment]
@jordonbiondo Great, many thanks!  Please ping me on this issue again when you are done.  I'll merge this PR then.

**Comment by lunaryorn** [comment]
@jordonbiondo Are you still interested in this PR?

**Comment by lunaryorn** [comment]
@jordonbiondo I'm closing this PR due to the lack of activity.  Please feel free to update and rebase on `master`, and I'll re-open and merge it.

**Pull request closed without merging**
