### PR TITLE
More stdin checkers

### PR DESCRIPTION
**Pull request by purcell**
Queueing up a few more stdin updates for checkers here...

Edit (@lunaryorn): List of patches already applied to `master`:

- [x] haml
- [x] coffee
- [x] tidy
- [x] gofmt
- [x] ~~hlint~~
- [x] shellcheck
- [x] yaml-ruby
- [x] php
- [x] perl
- [x] luac

I'll cherry-pick each of these individually and add the necessary changes to the error patterns.

### CODE REVIEW

**Comment by purcell** [comment]
If these look okay to you, feel free to merge this. Just waiting for Travis now, but I'm done for the night...

**Comment by lunaryorn** [comment]
@purcell I'll merge myself :)  It's great that you wait for Travis, but Travis doesn't actually test the syntax checkers anymore :wink:  Installing 70 tools just didn't scale :relaxed:

**Comment by purcell** [comment]
LOL, oops. I haven't actually tested these locally, sorry.

**Comment by lunaryorn** [comment]
My current workflow is to fetch the commits with Magit GH Pulls, test them on my VM, and then just cherry pick them :)

**Comment by lunaryorn** [comment]
@purcell These changes are great, but unfortunately they aren't enough.  Frequently you'll also have to adjust error patterns :disappointed_relieved: 

I'll go through these when I have time, and test them.

**Comment by lunaryorn** [comment]
@purcell We can't use standard input for `hlint` unfortunately, because it uses the file extension to determine whether the source is literate Haskell or not.  And unlike GHC it doesn't seem to provide a flag to explicitly set the source language :(

**Comment by lunaryorn** [comment]
@purcell I've merged all commits except of hlint and fixed error patterns if needed.  Thank you very much!

**Comment by purcell** [comment]
> We can't use standard input for hlint unfortunately, because it uses the file extension to determine whether the source is literate Haskell or not. And unlike GHC it doesn't seem to provide a flag to explicitly set the source language :(

Bummer.



> I've merged all commits except of hlint and fixed error patterns if needed. Thank you very much!

Great - thanks!

**Pull request closed without merging**
