### PR TITLE
Include config file in verification buffer if any

### PR DESCRIPTION
**Pull request by lunaryorn**
Closes GH-1021 which see.

LGTM, for the record.  @cpitclaudel ?

### CODE REVIEW

**Comment by lunaryorn** [comment]
Oh dear, MELPA still down?

**Comment by cpitclaudel** [comment]
LGTM. I guess (?) you could use a `-when-let` in there and save the `and` in `path`:

    ,@(-when-let (value (bound-and-true-p config-file-var))

But the behavior would be a bit different (it wouldn't print anything about config files when `config-file-var` has value nil)

(Unrelated: every time I see an `,@` followed by a a `list` with a single element inside a `when` I find myself wanting for a smarter version of `,@` that properly interpolates `Maybe`s)

**Comment by lunaryorn** [comment]
I'm not sure; `config-file-var` is a variable poiting to a symbol, not the symbol itself, so I don't think `bound-and-true-p` would work.

LGTM (because it didn't catch the first one).

**Comment by cpitclaudel** [comment]
Urgh, forgot that `bound-and-true-p` was a macro :) LGTM.

**Comment by lunaryorn** [comment]
MMh, looks like LGTM.co lost track of this one.  I'll use my admin privileges to merge.

**Pull request merged**
