### PR TITLE
Add new checker for Tcl

### PR DESCRIPTION
**Pull request by bsless**
Add new checker for Tcl

Add new checker for Tcl and general support for Tcl, including simple test file.

Also fix tiny grammatical error in a comment.

### CODE REVIEW

**Comment by bsless** [comment]
Thanks!
This is my first pull request and I'm still figuring things out, so, I'd love to add any entry you'd like if you could point me to the relevant location

**Comment by cpitclaudel** [comment]
Thanks to you! And welcome aboard :)
The change log is here: https://github.com/flycheck/flycheck/blob/master/CHANGES.rst.  You can edit it like the other files.

**Comment by bsless** [comment]
Thanks for the direction, got it figured out eventually 😄 
Seems like some tests fail due to disk quota. Do they need to be run again?

**Comment by cpitclaudel** [comment]
Sorry about the tests ! They're all good now.
Great job on your first Flycheck PR! Let's hope there'll be plenty more ^^

**Comment by bsless** [comment]
Thank you! It's been lots of fun, and your directions were helpful.
I hope to find more opportunities to contribute 😃 
Can I close the branch now?

**Pull request merged**
