### PR TITLE
Use docker to speed up CI

### PR DESCRIPTION
**Pull request by ghprince**
this is an effort to solve #1060 

It is still work in process, hacky and buggy code, please do not review until I think it is good enough.

I created the PR simply to trigger travis CI.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
I like this...we should ideally install dependencies for checkers and allow for all checker tests to run in CI as well..

**Comment by cpitclaudel** [comment]
@robbyoconnor We use to have a testing VM, but it was too much work keeping up with all the checkers.

**Comment by fmdkdd** [comment]
@robbyoconnor @cpitclaudel But any way to make it work without too much overhead would be swell ;)

I saw some thread on emacs-devel about a portable dumper branch that's supposed to fix the bug preventing Emacs to be included in a docker image.  Don't know how much helpful that would be; just mentioning.

**Comment by robbyoconnor** [comment]
not running checker tests in travis negates having them

**Comment by fmdkdd** [comment]
@ghprince Any update on this?  We're still very much interested in improving the CI situation, especially regarding the integration tests.

**Comment by fmdkdd** [comment]
Closing due to inactivity.  See also https://github.com/flycheck/flycheck/issues/1060#issuecomment-364676605.

**Pull request closed without merging**
