### PR TITLE
Use location of flake8 configuration file as working directory

### PR DESCRIPTION
**Pull request by fmdkdd**
Follow-up to https://github.com/flycheck/flycheck/issues/1644#issuecomment-553134516

### CODE REVIEW

**Comment by felker** [comment]
Thanks! This worked for me, but to be clear, the user does need to have a `.dir-locals.el` in the project root directory as suggested in https://github.com/flycheck/flycheck/issues/721#issuecomment-129556743 for this extension to work.

E.g. `M-x flycheck-compile RET python-flake8 RET` executed in the buffer for `__init__.py` in my MWE from https://github.com/flycheck/flycheck/issues/1644#issuecomment-553134516


With the `flycheck-flake8rc` variable set by `.dir-locals.el`:
```
python -c import\ sys\;sys.path.pop\(0\)\;import\ runpy\;runpy.run_module\(\"flake8\"\)\
 --format\=default --config /Users/felker/Downloads/flycheck-flake-mwe/setup.cfg --stdi\
n-display-name\=/Users/felker/Downloads/flycheck-flake-mwe/test/__init__.py - < /Users/felker/Downloads/flycheck-flake-mwe/test/__init__.py
```

Without:
```
python -c import\ sys\;sys.path.pop\(0\)\;import\ runpy\;runpy.run_module\(\"flake8\"\) --format\=default --st\
din-display-name\=/Users/felker/Downloads/flycheck-flake-mwe/test/__init__.py - < /Users/felker/Downloads/flycheck-flake-mwe/test/__init__.py
/Users/felker/Downloads/flycheck-flake-mwe/test/__init__.py:1:1: F401 'sys' imported but unused
```

**Comment by fmdkdd** [comment]
Yes, you need to tell `flycheck` the name of your flake8 configuration file.

I guess we could also try the usual ones, but that may be out of scope.

**Comment by cpitclaudel** [comment]
> I guess we could also try the usual ones, but that may be out of scope.

We could do that, and there are just three such names, but I think this is a flake8 bug.  THese paths are meaningless if they are not relative to the config file.  So I'd rather see a flake8 bug report before we start implementing workarounds

**Comment by felker** [comment]
@cpitclaudel good point; just found the `flake8` bug report:

https://gitlab.com/pycqa/flake8/issues/517

**Comment by cpitclaudel** [comment]
@felker Thanks, then I think we'll just wait for this to be fixed on their side.  Feel free to reopen this if that issue gets stale there and we need to work around it.

**Comment by cpitclaudel** [comment]
Reopened following #1722

**Comment by cpitclaudel** [comment]
See my comments in #1722 though.  Just looking for any flake8 config file isn't quite right.

**Comment by cpitclaudel** [comment]
Confirmed to work in 1722, and I think this rebase should address @felker's use case too.

**Comment by fmdkdd** [comment]
Sure, go ahead with this (I can't review my own PR).

**Pull request merged**
