### PR TITLE
Adds Asciidoctor as checker for AsciiDoc

### PR DESCRIPTION
**Pull request by fap-**
I broke `make specs` but I don't understand the error message. Help would be appreciated.

```
FAILED: Expected (asciidoctor) to `equal' nil

Ran 98 out of 99 specs, 1 failed, in 3.2 seconds.
```

### CODE REVIEW

**Comment by lunaryorn** [comment]
@fap- Thanks.  Could you explain how Asciidoctor is different from the checker we're currently using?

**Comment by fap-** [comment]
Asciidoctor adds additional features, syntax and enforces stricter rules.
You can read more  about the differences here: [Differences between Asciidoctor and AsciiDoc](http://asciidoctor.org/docs/asciidoc-asciidoctor-diffs/)

**Comment by lunaryorn** [comment]
@fap- So it's strictly better than asciidoc itself?

**Comment by fap-** [comment]
Since I don't have any experience with AsciiDoc I don't feel qualified to answer that.
The last official release for AsciiDoc seems to be from 2013?
http://www.methods.co.nz/asciidoc/CHANGELOG.html

We use Asciidoctor at work and it's actively developed and the creator is very responsive.

**Comment by lunaryorn** [comment]
@fap- In that case I'd say it is superior.  Could you move it before `asciidoc` so that it's preferred?

**Comment by fap-** [comment]
@lunaryorn I moved the position in `(defcustom flycheck-checkers ...)` Hope this was the right place?

**Comment by fap-** [comment]
@lunaryorn Any chance of merging this?

**Comment by fap-** [comment]
@flycheck/maintainers I know I've asked before but is there a chance of merging this checker now?
I'd be willing to maintain this recipe going forward. (referencing https://github.com/flycheck/flycheck/issues/1177#issuecomment-271336597)

**Comment by cpitclaudel** [comment]
Indeed, thanks for your work! We'll be happy to merge this, with the right CHANGES entry :)

**Comment by fap-** [comment]
Should be done :]

**Comment by fmdkdd** [comment]
Great!  Thank you for your contribution. 👍

**Pull request merged**
