### PR TITLE
Add sqlint checker

### PR DESCRIPTION
**Pull request by purcell**
Heya! Here's a new checker definition, but I haven't sent a PR for the VM repo. Can't easily see what's going on there, but happy to send a PR if you give me a pointer in the right direction. The checker is installable with `gem install sqlint`. :-)

### CODE REVIEW

**Comment by purcell** [comment]
I think I figured it out: https://github.com/flycheck/flycheck-vm/pull/3

**Comment by lunaryorn** [comment]
Cool!  Will take a look soon.

**Comment by lunaryorn** [comment]
I merged the PR.  Thanks for this cool thing, I must install it asap 😄

I'd like to ask you for a favour:  Can you give me a little SQL that triggers a warning from sqllint?  I'd like to have a test case for both patterns.

Besides, you don't need to open pull requests for such things. Please, do commit directly! 😀

**Comment by purcell** [comment]
> I'd like to ask you for a favour: Can you give me a little SQL that triggers a warning from sqllint? I'd like to have a test case for both patterns.

We don't have warnings yet, but @trezona-lecomte and I have one more day to work on this project, so watch this space, because we'll pack as much in as we can. For example, right now `sqlint` always stops on the first error, so tomorrow we'll make it resume at the next `;`. Stretch goal: optionally connect to a live DB and warn if the queries refer to nonexisting tables/columns. :-)

> Besides, you don't need to open pull requests for such things. Please, do commit directly! 😀

More polite this way... :-)

**Comment by lunaryorn** [comment]
@purcell Ah, ok.  I wish you a lot of fun and success for this projects.  It's definitely an absolutely useful thing!

**Pull request merged**
