### PR TITLE
Adding a Julia lint checker along with tests.

### LINKED ISSUE #502: Add support for Julia
I'd love to see support for Julia in flycheck.

@pao has written an elisp snippet here: https://gist.github.com/pao/e65029bf88650e592929 (from https://github.com/tonyhffong/Lint.jl/issues/43)

It should just be a matter of creating a pull request including this patch and some unit tests. I'm happy to do it unless anyone beats me to it.

### PR DESCRIPTION
**Pull request by Wilfred**
Fixes #502.

This checker can be slow (12 seconds on my old laptop), however this will improve hugely in the next version of Julia. It would be wonderful to see this in flycheck, let me know if you'd like me to change anything.

### CODE REVIEW

**Comment by lunaryorn** [comment]
@Wilfred Is there any update on this PR?  Is 0.4 released now?  Or did you make any progress with using a persistent process?

**Comment by Wilfred** [comment]
Sorry, I haven't forgotten this but haven't had an opportunity to work on this since Christmas. I still intend to, it's important to me.

0.4 isn't out yet, so I plan to go the persistent process route.

**Comment by lunaryorn** [comment]
@Wilfred What is the state of this now?

**Comment by Wilfred** [comment]
Sorry, I don't have time to work on this at the moment. I'd really like to explore the new flycheck API, but I'm not working on this at the moment. If I have an opportunity I'll send a new PR (or when Julia 0.4 comes out, this will be much easier).

**Comment by randre03** [comment]
@Wilfred and @lunaryorn By chance has there been any change or improvement to the chances of flycheck supporting Julia with or without Lint.jl now that we're in 2016 and Julia is at 0.4.3?

**Comment by lunaryorn** [comment]
@randre03 I for my part cannot tell whether a Julia checker would be possible now; I do not know Julia at all.

**Comment by gdkrmr** [comment]
https://github.com/gdkrmr/flycheck-julia

**Pull request closed without merging**
