### PR TITLE
Rust cargo

### PR DESCRIPTION
**Pull request by mkpankov**
Fix https://github.com/flycheck/flycheck-rust/issues/8

I'd appreciate a thorough code review: I'm not sure I did right with predicate, but then I'm also not sure if existing Rust checker has predicates right. I don't get why existing checker is invoked when `flycheck-rust-crate-root` is not defined.

Credits to @utkarshkukreti, @tomjakubowski for initial versions of the checker.

### CODE REVIEW

**Comment by mkpankov** [comment]
:cry: I must be doing something very stupid and wrong, can't pass the tests.

**Comment by mkpankov** [comment]
\o/

**Comment by mkpankov** [comment]
Is there anything blocking this?

**Comment by lunaryorn** [comment]
@mkpankov No, but I haven't yet had the time to review it. Please be a little patient :relaxed:

**Comment by mkpankov** [comment]
@lunaryorn Right, sorry; just got overexcited for flycheck working on my Rust projects finally :stuck_out_tongue:

**Comment by lunaryorn** [comment]
@mkpankov I'm happy to see that you're so excited, so I've moved the issue to the top of [our board](https://waffle.io/flycheck/flycheck), and will review and merge asap.  Still, that's not before this weekend, because I've got these god-damn social obligations :joy: on every single evening in this week :relaxed:

**Comment by lunaryorn** [comment]
@mkpankov I've tested it locally and it works well.  I'll merge it soon, but I'll first refactor the Rust unit tests and add some tests for this syntax checker.  Please have a little more patience :relaxed:

**Comment by lunaryorn** [comment]
@mkpankov Finally merged now!  Sorry for the long delay, and many thanks for this checker!

**Comment by mkpankov** [comment]
:fireworks:

**Comment by markuskobler** [comment]
So have just updated to the latest flycheck and looks like rust-cargo is throwing the following error which I assume is due to the last change.
```
Suspicious state from syntax checker rust-cargo: Checker rust-cargo returned non-zero exit code 101, but no errors from output: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target

Checker definition probably flawed.
```

Have tried digging through the code but not quite sure what I should be looking at to fix the issue. Any ideas what I might be doing wrong?

**Comment by markuskobler** [comment]
I should also mention I tried using the latest stable version of rust and the nightly build (2015-11-19)

**Comment by lunaryorn** [comment]
See https://github.com/flycheck/flycheck-rust/issues/16

**Comment by markuskobler** [comment]
Ah thats the same issue thanks

**Comment by Wilfred** [comment]
Can this be closed given that https://github.com/flycheck/flycheck/pull/772 has been merged? Should we be recommending that users just use flycheck now?

**Comment by mkpankov** [comment]
@Wilfred I guess you meant some other issue, since this itself is #772.

And no, https://github.com/flycheck/flycheck-rust/issues/16 can't be closed unfortunately, as the support is lacking in completeness and correctness.

**Pull request closed without merging**
