### PR TITLE
Add markdown lint checker

### PR DESCRIPTION
**Pull request by marsam**
Add markdown lint checker using https://github.com/mivok/markdownlint

Edit (lunaryorn): Connects to #839

### CODE REVIEW

**Comment by lunaryorn** [comment]
@marsam Thank you very much!  That's a nice addition.  Looks good so far, but might I ask you to also add support for the `--style` option, via `(config-file …)`?  Take a look at `javascript-eslint` for instance to see how this feature is used.

That'd be really awesome :relaxed:

**Comment by marsam** [comment]
Hi, I've added support for `--style` flag

**Comment by cpitclaudel** [comment]
I think our migration away from TexInfo caused conflicts :/ @marsam, could you update this PR to include documentation in RST format? Sorry for the merging delay! And thanks for your contribution :)

**Comment by marsam** [comment]
Updated

**Comment by lunaryorn** [comment]
@marsam I've finally merged this syntax checker.  Sorry for the delay, and thanks for your contribution! :+1:

**Pull request closed without merging**
