### PR TITLE
Add jsonnet checker

### PR DESCRIPTION
**Pull request by mgyucht**
This PR adds a checker to flycheck supporting the Jsonnet templating language. See https://jsonnet.org for details about the language.

### CODE REVIEW

**Comment by mgyucht** [comment]
Done!

**Comment by mgyucht** [comment]
Not exactly sure what failed here... @fmdkdd could you provide any insight?

**Comment by mgyucht** [comment]
@fmdkdd Apparently the __init__ method of HTMLXrefDB was missing a doccomment, so I added one...? The tests seem to pass now.

**Comment by fmdkdd** [comment]
Strange... why did `flake8` not complain the first time?  The pip packages should have been cached, so I don't think `flake8` could have been updated between your two commits...

Anyway,  LGTM.  Could you squash your commits before I can merge?  One commit for the `__init__` docstring, and one commit for the rest would be best.

**Comment by mgyucht** [comment]
Commits squashed! Thanks for your help with this!

**Comment by fmdkdd** [comment]
Great!  Thank you for a fine patch.

**Pull request merged**
