### PR TITLE
Use custom fringe indicators [#743]

### PR DESCRIPTION
**Pull request by lunaryorn**
New uniform indicators, inspired by Syntastic's indicators:

napkin 20 09 15 12 41 41 nachm

I find these much nicer than the default ones, and a uniform indicator make it easier to tell Flycheck indicators apart from other fringe icons.

Inviting @purcell @cpitclaudel @tonini and @syl20bnr for your feedback :)

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Looks beautiful! One small thing is that giving them the same shape might make it trickier for people with bad eyesight to tell them apart. Since the underlines have the same color as the indicators, this change might be removing a shape-based clue that some might have depended on.

Can we fit three `>` signs in the fringe? So we'd have `>`, `≫`, and `⋙` for info, warning, and error. Alternatively, we could just have `>` for info and `≫` for warning and errors (then the only risk would be confusing warnings and errors, which isn't that bad). This would also be consistent with indicators used by some mail programs. 

But yes, these look great!

**Comment by cpitclaudel** [comment]
Ah, looking at the implementation it might be tricky to fit three `>`s. Then maybe just moving `info` messages to a single `>` would do?

**Comment by lunaryorn** [comment]
@cpitclaudel I've thought about this point as well, but I don't think it's a real issue.  I guess even colour-blind people would rather customize their theme to use differentiable colours than relying on the fringe indicators.  These are just not helpful for this purpose:  They are too small, and they're not actually related to the error _at point_.

Syntastic and Spacemacs have been using uniform indicators ever since, and I'm not aware of any issues ever coming up with regards to the shape.

I think we can just try and use uniform indicators.  If people actually relied on the indicator shape they'll come here and report an issue, and then we can still try to find a better solution :relaxed:

**Comment by cpitclaudel** [comment]
Seems quite reasonable :)

**Comment by syl20bnr** [comment]
I like it and it makes the UI less heavy for the eyes.

Even for not color-blind people there is the issue of not being able to
distinguish the different type of indicators if a theme decide to do so.

In Spacemacs with leuven theme the dots are all the same color and this is
even worst in Spacemacs because the lighter in the modeline relies also on
the colors. This is a real problem.

What I planed in Spacemacs is to add an option for color blind people that
replaces the dots in modeline by e, w, and i.

Jenkins ships with blue/red status colors instead of green/red to fix the
issue for color blind people. In Flycheck blue is already taken for info so
it may be tricky to do this.

I'm not sure this is an issue in pure flycheck because the lighter is more
specific.

Le dimanche 20 septembre 2015, Clément Pit--Claudel <
notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :

> Seems quite reasonable :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flycheck/flycheck/pull/750#issuecomment-141783208>.
>


-- 
-syl20bnr-

**Comment by lunaryorn** [comment]
> I like it and it makes the UI less heavy for the eyes.

Great, thank you :)

> Even for not color-blind people there is the issue of not being able to
> distinguish the different type of indicators if a theme decide to do so.

Did you actually get issue reports or feedback from colour-blind people for Spacemacs?

> Jenkins ships with blue/red status colors instead of green/red to fix the
> issue for color blind people. In Flycheck blue is already taken for info so
> it may be tricky to do this.

Flycheck does not explicitly choose any colours.  By default, its faces inherit from the standard `error`, `warning` and `info` faces respectively, and anything beyond that is up to the theme.   IOW, it's the theme (solarized probably?) that “takes” blue, not Flycheck itself.

And I think colour-blind people will already have chosen a theme which is friendly to colour-blindness, simply because the issue arises at any lace where Emacs uses colours, i.e. virtually anywhere.

**Comment by purcell** [comment]
Big thumbs-up from me.

**Comment by tonini** [comment]
Looks really great! :+1:

**Comment by lunaryorn** [comment]
Thank you all for your feedback and for the discussion.  I've merged this branch now, let's see whether folks enjoy the new indicators.

**Comment by syl20bnr** [comment]
> Did you actually get issue reports or feedback from colour-blind people for Spacemacs?

Nope I haven't, rather surprising. You are right, color-blind people will select appropriate themes for them.

Nice to see these indicators merged :+1:

**Pull request merged**
