### PR TITLE
ruff: --output-format=text replaced with --output-format=concise

### PR DESCRIPTION
**Pull request by berquist**
ruff 0.5.0 changed this flag in https://github.com/astral-sh/ruff/pull/12010.

### CODE REVIEW

**Comment by manufactory** [comment]
Works here with `ruff 0.5.0`

**Comment by bbatsov** [comment]
What will happen to people using older versions of `ruff` with this change?

**Comment by wyuenho** [comment]
--output-format has been deprecated since 0.2.0. The original PR took too long to merge, so it wasn't discovered as it continued to work up until 0.4.5.

**Comment by bbatsov** [comment]
I see. Well, this has to be rebased on top of `master` and a changelog entry should be added. I'll wait to see if @berquist will do this soon, otherwise I'll just do it myself.

**Pull request merged**
