### PR TITLE
Flycheck checker for Javascript using Flow

### PR DESCRIPTION
**Pull request by lbolla**
As requested, let's support Flow as a standard Javascript checker.

### CODE REVIEW

**Comment by lbolla** [comment]
I had troubles with `make install` and `test/run.el (new-checker-for javascript)`. It complains that I miss some libraries (namely, `let-alist`) even if that library *is* installed in my `~/.emacs.d/` (using `list-packages` etc.).
Therefore I have not committed a unittest for the checker. I am happy to do so if you help me to figure out the above issues...

**Comment by lunaryorn** [comment]
@lbolla Thank you. 

We use a separate package environment for our unit tests with [Cask](http://cask.github.io).  You need to run `cask install` first.  But I can write the test myself, I'll just need a small Javascript snippet that causes a Flow error.  If you could drop that into `test/resources/language/javascript/` in this PR, that'd be perfect :relaxed:

The more important question is however how Flow relates to the other Javascript checkers.  Would a user reasonably want to use both Flow and for ESLint for example in the same buffer?

**Comment by lbolla** [comment]
OK. I've added a snippet to trigger an error with Flow.
I've also run `cask install` and `make compile` worked. But `test/run.el` failed 4 tests:
`Ran 33 tests, 18 results as expected, 4 unexpected, 11 skipped (2015-11-14 11:01:19+0000)`

**Comment by lunaryorn** [comment]
Flycheck does not provide `javascript-jslint`.  Do you think it'd make sense to run flow after `jshint` and `eslint`?

**Comment by lbolla** [comment]
Yes, sure!

**Comment by Skinney** [comment]
Is there anything blocking the inclusion of this?

**Comment by lunaryorn** [comment]
@Skinney My time, mainly.  The pull request would need to be updated for chaining, see my comment above, and tested; but I'm short of time, and hence my focus is currently on improving our documentation for contributors and maintainers so that in future we'll have more people than me to merge pull requests.

Furthermore, I don't think that this is particularly important, as flow is already available in a perfectly working 3rd party package, hence it's not that urgent to integrate it in Flycheck.

However, if you've got important reasons to merge it as soon as possible I'd can priorise it differently :relaxed:

**Comment by Skinney** [comment]
I didn't mean to rush you, I was just being curious. I can probably try to invest some of my own time next week :)

**Comment by aaronjensen** [comment]
fwiw, I prefer to run eslint after flow. Flow can pick up on real problems with code, eslint just style problems, so I tend to think of flow more as a compile step. Also, this flychecker has changed a decent amount on the main repo: https://github.com/lbolla/emacs-flycheck-flow/blob/master/flycheck-flow.el

**Comment by lunaryorn** [comment]
@aaronjensen I'm holding off new syntax checkers for languages until #836 is solved, because complex syntax checker chains are hard to maintain and control with the current system.

I'd recommend to use the 3rd party package for now; this pull request currently serves as a reminder to integrate flow after #836 is solved.

**Comment by fmdkdd** [comment]
@aaronjensen Since #836 is on hold, we'd rather merge new syntax checkers than hold off indefinitely.  In fact, it will also be easier to see all the usages of `next-checker` that way.

Are you still willing to update this PR?

**Comment by cpitclaudel** [comment]
Closing because we haven't had updates on this for a while.  As @fmdkdd mentionned, we'd be happy to merge this if someone steps up to refresh this PR, and hopefully we can handle new PRs more expeditiously. Thanks!

**Pull request closed without merging**
