### PR TITLE
Tramp support ( fixes #1777 )

### LINKED ISSUE #1777: Flycheck breaks over TRAMP
Thank you for taking the time to report an issue and improve Flycheck.  This template is for **actual bugs you observed**.  If you have trouble setting up Flycheck, or if you have a question, please use the relevant issue template instead.

## Checklist
- [ X ] I have checked existing issues for potential duplicates before creating this one.
- [ X ] I have read the [Troubleshooting guide][].

## Bug description
pylint throws errors when editing a python file over tramp when failing to find .pylintsc

## Steps to reproduce
1. Open a python file over TRAMP with pylint or mypy enabled
2. Edit the file
3. See error
```
Suspicious state from syntax checker python-pylint: Flycheck checker python-pylint returned non-zero exit code 1, but its output contained no errors: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/runpy.py", line 209, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/__main__.py", line 18, in <module>
    pylint.run_pylint()
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/lint/run.py", line 287, in __init__
    linter.read_config_file(verbose=self.verbose)
  File "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/config.py", line 741, in read_config_file
    raise OSError("The config file {:s} doesn't exist!".format(config_file))
OSError: The config file /ssh:ashton-dev-juliet:/home/ubuntu/src/cme-pre-ingestion/.pylintrc doesn't exist!

Try installing a more recent version of python-pylint, and please open a bug report if the issue persists in the latest release.  Thanks!
Suspicious state from syntax checker python-mypy: Flycheck checker python-mypy returned non-zero exit code 2, but its output contained no errors: mypy: can't read file '/ssh:ashton-dev-juliet:/home/ubuntu/src/cme-pre-ingestion/ingest.py': No such file or directory
```

- [ X ] I have read https://emacs.stackexchange.com/questions/28429/how-do-i-troubleshoot-emacs-problems

## Expected behavior
I expected flycheck to work or ignore remote files.

## System configuration
```
Syntax checkers for buffer ingest.py in python-mode:

First checker to run:

  python-flake8
    - may enable:         yes
    - executable:         Found at /usr/bin/python3
    - configuration file: Not found
    - `flake8' module:    Found at "/home/ahonnecke/.local/lib/python3.8/site-packages/flake8/__init__.py"
    - next checkers:      python-pylint, python-mypy

Checkers that may run as part of the first checker's chain:

  python-pylint
    - may enable:         yes
    - executable:         Found at /usr/bin/python3
    - configuration file: Found at "/ssh:ashton-dev-juliet:/home/ubuntu/src/cme-pre-ingestion/.pylintrc"
    - `pylint' module:    Found at "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/__init__.py"
    - next checkers:      python-mypy, python-mypy

  python-mypy
    - may enable:         yes
    - executable:         Found at /home/ahonnecke/.local/bin/mypy
    - configuration file: Not found

Checkers that could run if selected:

  python-pycompile  select
    - may enable:    yes
    - executable:    Found at /usr/bin/python3
    - next checkers: python-mypy


The following syntax checkers are not registered:

  - lsp

Try adding these syntax checkers to `flycheck-checkers'. Flycheck Mode is enabled. Use C-u C-c ! x
to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20200316.310)
Emacs version:    26.3
System:           x86_64-pc-linux-gnu
Window system:    x
Syntax checkers for buffer ingest.py in python-mode:

First checker to run:

  python-flake8
    - may enable:         yes
    - executable:         Found at /usr/bin/python3
    - configuration file: Not found
    - `flake8' module:    Found at "/home/ahonnecke/.local/lib/python3.8/site-packages/flake8/__init__.py"
    - next checkers:      python-pylint, python-mypy

Checkers that may run as part of the first checker's chain:

  python-pylint
    - may enable:         yes
    - executable:         Found at /usr/bin/python3
    - configuration file: Found at "/ssh:ashton-dev-juliet:/home/ubuntu/src/cme-pre-ingestion/.pylintrc"
    - `pylint' module:    Found at "/home/ahonnecke/.local/lib/python3.8/site-packages/pylint/__init__.py"
    - next checkers:      python-mypy, python-mypy

  python-mypy
    - may enable:         yes
    - executable:         Found at /home/ahonnecke/.local/bin/mypy
    - configuration file: Not found

Checkers that could run if selected:

  python-pycompile  select
    - may enable:    yes
    - executable:    Found at /usr/bin/python3
    - next checkers: python-mypy


The following syntax checkers are not registered:

  - lsp

Try adding these syntax checkers to `flycheck-checkers'. Flycheck Mode is enabled. Use C-u C-c ! x
to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20200316.310)
Emacs version:    26.3
System:           x86_64-pc-linux-gnu
Window system:    x
```

Emacs configuration:
- [ ] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [ ] Doom Emacs
- [ X ] Other shared configuration (prelude heavily modified)

## Additional notes
Apologies if this is a pylint or mypy issue.

### PR DESCRIPTION
**Pull request by FelipeLema**
Support remote commands using tramp ( fix #1777 )

### CODE REVIEW

**Comment by FelipeLema** [comment]
So, I personally think processes should be deferred to an [`async`](https://github.com/jwiegley/emacs-async/) in tramp buffers.

Why? Because Tramp will block Emacs when launching processes using threads. While we've had (non-concurrent) threads for a while, using them is not reliable when doing several calls at the same time with tramp (see https://github.com/cjohansson/emacs-ssh-deploy/issues/57#issuecomment-490476712 ).

I've had quite a lot of tramp blocking experience and I've found that the `async` is very comfortable to use (won't block, simple to use).

Will first break the use of processes into a separate class (something like "running checker command"). Then, re-implement functionality for Emacs processes and finally extend for an async-future.

**Comment by FelipeLema** [comment]
AY, CHIHUAHUA

I just found that the assumption "processes return right away, they never block" is all over the code. I'll try to re-code some stuff as asynchronous / event oriented first.

This feature will take a while. Help is most welcome.

**Comment by bjc** [comment]
Help may be on the way! I have also found myself in a situation where I'd like to be running flycheck over TRAMP and have stumbled on to this issue.

I looked at the commit… but there doesn't appear to be anything there other than a change to a docstring.

Can you give me an idea of what you've done, what's in store, and where you need help?

**Comment by FelipeLema** [comment]
oh, right, I haven't uploaded much

Bare with me, this might take a while.

You might've noticed that calling `start-process` halts Emacs for a few seconds. This has improved in Tramp nightly (within Emacs nightly code), but it may still hang Emacs a bit.

This halting is caused because of Tramp internals in which it does several checks and setup to provide a remote process that can be handled properly (think signals).

To address this "don't halt when launching process" problem, some (quote required) have found that using `make-thread` is enough, although I personally found that using the `async` package is consistent. If you choose to go either way, you'll have to re-code flycheck with an asynchronous model.

The good news is that some of flycheck can be easily translated, since this is already done using processes (start checker in background) and sentinels (report errors-and-warnings using a callback). It would have to be re-coded into `async` futures (background checker) and callbacks (report).

Now, the bad news is that this model does not fit all of flycheck. There are some functions that are synchronous (call and wait for returned value) that need to be re-written from scratch into an asynchronous model. Namely:

- `flycheck-verification-result`
- `flycheck-verify-generic-checker`

I believe these (and others?) must be re-written so to keep flycheck snappy. Everything involving "calling a command / process" should be assumed to be laggy and must be avoided.

**Comment by FelipeLema** [comment]
By now it should be clear the core changes for "running checker".

You can see a lot of "TODO (async)" there.

**Comment by bjc** [comment]
After looking at the amount of work involved, I decided to also check out the built-in Flymake, since it's apparently improved a lot recently, and decided it would be easier to add language support that way rather than trying to do it in Flycheck, which is just too complicated for me to tackle in a reasonable amount of time, and Flymake is good enough for my purposes for now.

Sorry to get your hopes up. Good luck with the changes!

**Comment by FelipeLema** [comment]
keep an eye out for `flymake-cc`. It made my Emacs tramp experience most sluggish and it took me several days to find it as the smoking gun (I was using eglot.el + flymake then)

**Comment by FelipeLema** [comment]
Related: #1816

**Comment by FelipeLema** [comment]
kinda obvious right now, but I'm not actively pursuing this

**Pull request closed without merging**
