### PR TITLE
Improve the documentation of set-indication-mode

### PR DESCRIPTION
**Pull request by mssdvd**
I also updated the left-fringe width to 0 px. Is there any reason why it was set to 1?

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Very nice, thanks a lot.  I left to 1px originally because otherwise there's no visual distinction between the fringe and the margin (I wish there was a way to change the margin's background color, to make ti more visually distinct; maybe we should request this on the Emacs side and change to 0px once it's implemented?)

**Comment by mssdvd** [comment]
Yeah, sure!

**Comment by cpitclaudel** [comment]
Perfect.  I merged the first commit into flycheck-32 and master from the command line, with a small tweak (`left-margin` wasn't quoted).

**Comment by cpitclaudel** [comment]
I'll open a feature request on the Emacs tracker and then I think we're good :)

**Comment by cpitclaudel** [comment]
The feature request is at https://debbugs.gnu.org/cgi/bugreport.cgi?bug=26909 ; there was already one, so I added an extra message.

**Pull request closed without merging**
