### PR TITLE
Add flycheck-ghc-packages, a list of visible GHC packages

### PR DESCRIPTION
**Pull request by gracjan**

### CODE REVIEW

**Comment by gracjan** [comment]
Hej, what up with this one?

**Comment by lunaryorn** [comment]
@gracjan I'm not sure that we still need it.  It's only for the rare case of conflicting identifiers in different packages, and you can already use `flycheck-ghc-args` to add the required arguments directly.

**Comment by lunaryorn** [comment]
@gracjan Besides, sorry for the delay, I had completely forgotten about this PR in the aftermaths of the new generic checkers.

**Comment by gracjan** [comment]
Generic args revolution? How could I have missed that!

I remember arguing for generic args some time ago and you were against. What has changed your mind?

Closing as not useful anymore.

**Comment by lunaryorn** [comment]
GHC and some other checkers have just too many special cases, which would require special options.  Also, it's easier for extensions to extract settings from build systems, if they can just add compiler options from the build system directly.

I'd still like to have dedicated options for common settings, though, like include directories and warning levels and stuff like that.  It's easier to use dedicated options as file local variables, and we can provide a better customise interface for dedicated options.

**Pull request closed without merging**
