### PR TITLE
javascript-eslint fix config detection in eslint 6

### LINKED ISSUE #1593: Config discovery no longer works in eslint 6
the function 
```lisp
(defun flycheck-eslint-config-exists-p ()
  "Whether there is a valid eslint config for the current buffer."
  (let* ((executable (flycheck-find-checker-executable 'javascript-eslint))
         (exitcode (and executable (call-process executable nil nil nil
                                                 "--print-config" "."))))
    (eq exitcode 0)))
```
runs `eslint --print-config .` yet in eslint 6.0 running that command fails all the time, with 
```
Oops! Something went wrong! :(

ESLint: 6.0.1.

The '--print-config' CLI option requires a path to a source code file rather than a directory.
See also: https://eslint.org/docs/user-guide/command-line-interface#--print-config
```

An answer could potentially be something like `eslint --print-config index.js`

### PR DESCRIPTION
**Pull request by ar1a**
fixes #1593

### CODE REVIEW

**Comment by ar1a** [comment]
oh my god the commit message is misspelled :sob:

**Comment by cpitclaudel** [comment]
Thanks! That typo looks like the perfect job for a `git rebase` or `git commit --amend` :)

**Comment by cpitclaudel** [comment]
I think you're missing a closing parenthesis `)`

**Comment by ar1a** [comment]
how did I miss that?! I shall fix it in the morning

**Comment by fmdkdd** [comment]
Closing in favor of #1588.

**Pull request closed without merging**
