### PR TITLE
Show :enabled in verification buffer

### PR DESCRIPTION
**Pull request by lunaryorn**
Follow up to #1098 and #1105

### CODE REVIEW

**Comment by cpitclaudel** [comment]
LGTM, with one small worry: if I start flycheck, then create the config file, C-c ! v will show "automatically disabled" but "config file found".  This might be confusing?

**Comment by lunaryorn** [comment]
@cpitclaudel I tried to reproduce that, but failed.

With no config:

```
  javascript-eslint (disabled)
    - enabled:     Automatically disabled!
    - executable:  Found at /Users/swiesner/.local/bin/eslint
    - config file: missing
```

After adding a config:

```
  javascript-eslint (disabled)
    - enabled:     t
    - executable:  Found at /Users/swiesner/.local/bin/eslint
    - config file: found
```

I think it's confusing that it says "enabled t" while listing it as "disabled" (which it is), but I can't reproduce the particular state that you have seen.

Can you give me a step-by-step recipe?

**Comment by lunaryorn** [comment]
I've pushed a change to the wording.  It now says "may enable": 

```
  javascript-eslint (disabled)
    - may enable:  yes
    - executable:  Found at /Users/swiesner/.local/bin/eslint
    - config file: found
```

I think that's clearer, isn't it?   @cpitclaudel 

/cc @Simplify

**Comment by cpitclaudel** [comment]
Very nice! I like it.  Sorry for the confusing comment; just shows how poor my brain is as interpreting ELisp :)
Maybe after this is complete one of us can make a separate PR that adds a clickable link that says "enable now" next to "may enable"

**Comment by lunaryorn** [comment]
LGTM, too, then 😎 

> Maybe after this is complete one of us can make a separate PR that adds a clickable link that says "enable now" next to "may enable"

That's a nice idea—never thought of this 👍.  Please make an issue for it so that we don't forgot.  I think I won't get to do it anytime soon, I'd really like to get the new chaining and the updates to the docs done, but there's always so little time 😟

**Pull request merged**
