### PR TITLE
Allow specifying end column and end line for errors

### PR DESCRIPTION
**Pull request by yyoncho**
- backends like lsp-ui could provide that data.

Before:
before

After:
after

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Did you see https://github.com/flycheck/flycheck/pull/1400 ?

**Comment by yyoncho** [comment]
> Did you see #1400 ?

Yes - but it is stalled for not being backward compatible(unless I am mistaken) so I went for implementation that does not break existing backends(forgot to mention in the PR that a version with one `region` property). I don't mind rejecting this PR in favour of #1400 - it will for me too.

**Comment by yyoncho** [comment]
ping?

**Comment by cpitclaudel** [comment]
Sorry for the delay (and thanks for the ping).  I think this might be the most reasonable approach.  We can fix the region performance issue at a later point.  Let me just go through #1400 to see what else was relevant in that code.

**Comment by cpitclaudel** [comment]
Closing in favor of #1676.  Thanks for the PR.

> I went for implementation that does not break existing backends

Note that as written, this PR isn't in fact backwards compatible, because the call to (flycheck-error-end-column err) will fail if `err` is created by a package compiled with a previous version of flycheck.

**Pull request closed without merging**
