### PR TITLE
remove pkg-info and epl package dependency

### PR DESCRIPTION
**Pull request by conao3**
remove `pkg-info` and `epl` package dependency.

see this log.
```
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Package refresh done
Contacting host: melpa.org:443
Contacting host: melpa.org:443
  INFO     Scraping files for epl-autoloads.el... 
  INFO     Scraping files for epl-autoloads.el...done
Checking /home/conao/dev/repos/keg.el/.keg/27.1/elpa/epl-20180205.2049...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/epl-20180205.2049/epl-autoloads.el...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/epl-20180205.2049/epl-pkg.el...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/epl-20180205.2049/epl.el...
Done (Total of 1 file compiled, 2 skipped)
  INFO     Scraping files for pkg-info-autoloads.el... 
  INFO     Scraping files for pkg-info-autoloads.el...done
Checking /home/conao/dev/repos/keg.el/.keg/27.1/elpa/pkg-info-20150517.1143...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/pkg-info-20150517.1143/pkg-info-autoloads.el...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/pkg-info-20150517.1143/pkg-info-pkg.el...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/pkg-info-20150517.1143/pkg-info.el...
Done (Total of 1 file compiled, 2 skipped)
Contacting host: melpa.org:443
Parsing tar file... 
Parsing tar file...done
Extracting... \ 
Extracting...done
  INFO     Scraping files for dash-autoloads.el... 
  INFO     Scraping files for dash-autoloads.el...done
Checking /home/conao/dev/repos/keg.el/.keg/27.1/elpa/dash-20200803.1520...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/dash-20200803.1520/dash-autoloads.el...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/dash-20200803.1520/dash-pkg.el...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/dash-20200803.1520/dash.el...
Done (Total of 1 file compiled, 2 skipped)
Contacting host: melpa.org:443
Parsing tar file... 
Parsing tar file...done
Extracting... \ 
Extracting...done
  INFO     Scraping files for flycheck-autoloads.el... 
  INFO     Scraping files for flycheck-autoloads.el...done
Checking /home/conao/dev/repos/keg.el/.keg/27.1/elpa/flycheck-20200610.1809...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/flycheck-20200610.1809/flycheck-autoloads.el...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/flycheck-20200610.1809/flycheck-buttercup.el...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/flycheck-20200610.1809/flycheck-ert.el...
Compiling /home/conao/dev/repos/keg.el/.keg/27.1/elpa/flycheck-20200610.1809/flycheck-pkg.el...
Compiling
/home/conao/dev/repos/keg.el/.keg/27.1/elpa/flycheck-20200610.1809/flycheck.el...
```

`flycheck` depends only one function fom `pkg-info`.
But depends one function depends two packages, `pkg-info`, `epl`.
Such a dependency is undesirable where it has nothing to do with flycheck.
Implementing a simple function eliminates the dependency from the two packages.

### CODE REVIEW

**Comment by fmdkdd** [comment]
Even if it's just one function, it's code that we don't have to maintain, and doesn't have to be duplicated.  If you have other packages that depend on `pkg-info`, then the cost is also amortized.
Thanks anyway for the thoughful PR.

**Comment by conao3** [comment]
First place, I don't think the version info is useful. Do you really need version information in users bug report?

Let's say there is a bug report for me. I manage a lot of packages, and the first thing I get them to do is to install the latest version from MELPA and run it with `emacs -q`.
I don't see the need to include two non-essential packages.

**Comment by liuyinz** [comment]
@fmdkdd Please review this pr : https://github.com/flycheck/flycheck/pull/1896 , I use builtin package to check version instead.

**Comment by Jturnerusa** [comment]
You should be able to achieve the same behavior without third party packages with a fairly trivial change, that way the code is actually maintained with emacs itself.

It's also worth noting that both pkg-info and epl are entirely dead and unmaintained for *years* at this point, so if they could be removed fairly easily, it would very much be worth it.

**Pull request closed without merging**
